---
title: "Fishing for Significance: Hypothesis Testing Involving Multiple Testing with Bayesian and Frequentist Tools"
---
**Presenter:** Barış Karahan, Tilburg University

**Co-authors:** Marcel van Assen (Tilburg University)

### Abstract {.unlisted .unnumbered}

This study investigates the consequences of p-hacking through selective reporting of multiple dependent variables. We demonstrate analytically how testing k independent and identically distributed variables and reporting only the most significant leads to inflated Type I error rates and exaggerated effect sizes. Extending these findings to Bayesian inference, we show that Bayes Factors (BFs) are also susceptible to distortion under multiple testing, challenging the claim that Bayesian methods are robust to fishing in general. We examine how the distribution of BF and estimated effect sizes changes under multiple testing, and show that the BF is consistent, that is, in the long run the right decision is made with certainty. Akin to power-analyses, we derive the required sample size to make the right decision with hypothesis testing using the BF, under selective reporting. Our findings underscore the need for transparent reporting and rigorous correction strategies to mitigate the impact of undisclosed multiplicity on scientific inference.
