---
title: "Types of Statistical Arguments in Empirical Research in Psychology"
---
**Presenter:** Gustavo Andres Marquez Flores, Rijksuniversiteit Groningen

**Co-authors:** Rink Hoekstra (University of Groningen), Henk Kiers (University of Groningen), Don van Ravenzwaaij (University of Groningen)

### Abstract {.unlisted .unnumbered}

Numerous solutions have been proposed to address the problem of statistical misuse and misunderstanding in research in psychology. Some say that redefining or even removing null hypothesis significance testing (NHST) is the first step toward reformation. After all, researchers may follow NHST guidelines as though they were performing a ritual, without giving it much thought (Gigerenzer, 2004). Even so, we believe that the large and deserved focus on issues with NHST might have diverted attention from how or whether scientists are actually engaging in critical, statistical thinking while doing research. Perhaps related, the focus has been very much on errors in statistical reasoning, rather than the nature of statistical reasoning itself.

We take a different approach by extracting arguments of papers written by empirical researchers, regardless of their validity. We understand arguments to be a set of reasons offered to support or undermine a claim about or using statistical results (Weston, 2009). For their extraction, we are conducting a qualitative study using inductive content analysis (Hsieh & Shannon, 2005) to collect arguments from 42 empirical and meta-analytic studies from 7 highly cited psychology journals.
