---
title: "Non-Robustness in Log-Like Specifications"
---
**Presenter:** Jack Fitzgerald, Vrije Universiteit Amsterdam

**Co-authors:** Joop Adema (University of Innsbruck), Lenka Fiala (University of Ottawa and Institute for Replication), Essi Kujansuu (University of Innsbruck), David Valenta (University of Ottawa and Institute for Replication)

### Abstract {.unlisted .unnumbered}

Recent literature shows that when regression models are estimated on variables transformed with 'log-like' functions such as the inverse hyperbolic sine or ln(Z + 1) transformations, one can obtain (semi-)elasticity estimates of any magnitude by linearly re-scaling the input variable(s) before transformation. We systematically re-analyze the replication data of 46 papers whose main conclusions are defended by log-like specifications. Our replication findings motivate new theoretical and simulation results showing that in log-like specifications, unit scale can be used to overfit data, creating an uncontrolled multiple hypothesis testing problem that frequently yields spuriously significant results. In particular, 38% of the estimates we re-analyze sit in a 'sweet spot', where both upward and downward re-scalings of variables' units before transformation shrink test statistics. Consequently, published estimates in this literature are statistically significant over 40% more frequently than in the general economics literature.

We find that modest changes to model specification yield different statistical significance conclusions for 14–37% of estimates defending papers' main claims. We also show that for 99.8% of estimates, variables transformed with log-like functions do not meet data requirements for log-like specifications from a methodological recommendation cited by all papers in our replication sample. We synthesize and harmonize methodological guidelines and advocate for more robust alternative specifications, including normalized estimands, Poisson regression, and quantile regression.
