---
title: "Calculating True Values in Causal Inference Simulation Studies via Gaussian Quadrature"
---
**Speaker:** Alex Ocampo, Roche

**Co-authors:** Enrico Giudice (Novartis), Zachary R. McCaw (University of North Carolina Chapel Hill), Tim P. Morris (Novartis)

### Abstract {.unlisted .unnumbered}

Simulation studies are used to understand the properties of statistical methods. A key luxury in many simulation studies is knowledge of the true value (i.e. the estimand) being targeted. With this oracle knowledge in-hand, the researcher conducting the simulation study can assess across repeated realizations of the data how well a given method recovers the truth. In causal inference simulation studies, the truth is rarely a simple parameter of the statistical model chosen to generate the data. Instead, the estimand is often an average treatment effect, marginalized over the distribution of confounders and/or mediators. Luckily, these variables are often generated from common distributions such as the normal, uniform, exponential, or gamma. For all these distributions, Gaussian quadratures provide efficient and accurate calculation for integrands with integral kernels that stem from known probability density functions. We demonstrate through three applications how to use Gaussian quadrature to accurately and efficiently compute the true causal estimand. We also compare the pros and cons of Gauss-Hermite quadrature to Monte Carlo integration approaches, which we use as benchmarks. Overall, we demonstrate that Gaussian quadrature is an efficient accurate tool that fosters reliability and replicability in simulation studies.
