---
title: "Evaluating the Quality of LLM Feature Extraction: A Systematic Simulation Workflow"
---
**Speaker:** Daniel Heck, Philipps-Universität Marburg

**Co-authors:** Tim Angelike (Philipps-Universität Marburg)

### Abstract {.unlisted .unnumbered}

Large Language Models (LLMs) are increasingly used in scientific research for various tasks. In psychology and the social sciences, these models facilitate fast and automated feature extraction to measure constructs of interest. However, LLM applications afford a high degree of flexibility, with variations in prompt design, model family, complexity, and configuration possibly yielding different results and divergent conclusions. To help researchers navigate the multiverse of possible design choices, we propose a structured workflow for simulating a grid of different LLM specifications to assess feature extraction quality from a psychometric perspective, specifically using generalizability theory. We adopt the ADEMP (Aims, Data-generating mechanism, Estimands, Methods, Performance measures) template, originally developed for simulation studies of statistical methods (Siepe et al., 2024). This modified template supports researchers in planning and reporting simulation studies for LLM feature extraction, emphasizing critical design choices and essential details that should be reported in a scientific paper. In a pre-registered case study, we conduct a conceptual replication of Martínez et al. (2024) to examine how model choice, response format, and specific prompt design elements (e.g., the presence and type of examples) influence the quality of valence and arousal ratings. Furthermore, we assess the efficacy of various methods for aggregating repeated LLM ratings.
