---
title: "Recent criteria and simple rules for the required sample size to develop clinical prediction models: what does it matter?"
---
**Speaker:** Ewout Steyerberg, Julius Center, University Medical Center Utrecht

**Co-authors:** Toby Hackmann (Leiden), Ben van Calster (Leuven), Maarten van Smeden (Utrecht), Laure Wynants (Maastricht)

### Abstract {.unlisted .unnumbered}

**Background:** Adequate sample size is essential to the development of prediction models with binary outcomes. We aim to relate recent approaches to traditional rules of thumb ('simple rules') theoretically and empirically.

**Methods:** A well-known simple rule considers the events per variable (EPV), or events per parameter p (EPP, e.g. 'EPP>10', or 'EPP>20') to limit overfitting to small data sets. Another simple rule is to require a minimum absolute number of events (E) for reliable estimation of the overall event rate (e.g. 'E>100'). Recent criteria consider: 1) limited overfitting in predictor effect estimates ('global shrinkage s≥0.9'); 2) small optimism in Nagelkerke's R² ('δ(R²)≤0.05'); and 3) precise estimation of the overall event rate (margin of error <0.05).

**Results:** Simple rules and recent criteria 1 and 2 can be compared well for relatively rare events, where the number of events defines the effective sample size. Global shrinkage relates model fit (chi², equivalent to Area under the ROC curve c for a given event rate) to model complexity (parameters p): s=(chi² – p) / chi². At a 10% event rate, criterion 1 appears to correspond to the classic EPP>10 rule for an Area under the ROC curve (c) of 0.77, and EPP>20 for c= 0.69. Criterion 2 implied EPP>4 (largely irrespective of c). Criterion 3 considers the absolute error, while E=100 is approximately a 10% relative error, with agreement between criterion 3 and E=100 at a 30% event rate. We found good agreement for the EPP>10 rule and especially for a combination rule (E>100+10*p) with max(recent criteria) in a comparison of required sample size for 299 published COVID-19 prediction models.

**Conclusions:** Recent criteria are key to inform prospective prediction modeling efforts, while simple rules may still be sufficient to help appraise the quality of already developed prediction models.
