---
title: "Teaching Open Science and Reproducibility"
---
**Speaker:** Hanne Oberman, Utrecht University

### Abstract {.unlisted .unnumbered}

If we want methodologists to produce reproducible research, they should learn how to — sooner rather than later.

In this session, I want to:

- discuss how Open Science was adopted as core principle for education at Utrecht University;
- showcase how our department of Methodology & Statistics teaches reproducibility in statistics and data science; and
- engage with the audience to exchange ideas about teaching reproducibility.

At Utrecht University, 'Open Science' was recently added to the educational model, making it a core characteristic of our teaching. This means that students should encounter reproducibility at every stage of their academic career. In practice, however, each course coordinator may have to 'reinvent the wheel'. That's why the Community for Open Science in Education (COSiE) is developing a quality model for reusing teaching materials about Open Science and reproducibility.

In our statistics and data science education for the social sciences, learning about reproducibility is already part of the course aims all throughout the curriculum. Students first encounter the practices in their very first course at our university, then again in the two subsequent Bachelor level courses, and we even offer dedicated (post-)graduate courses about markup languages and reproducible programming in statistics.

Ideally, I would like to have more of an 'unconference' setting to discuss reproducibility as an educational topic. For example, how can we best make use of 'Open Educational Resources'? There are so many great initiatives to make use of (such as [FORRT](https://forrt.org/), [The Turing Way](https://the-turing-way.netlify.app/), [The Carpentries](https://carpentries.org/), etc.), but administrators often prefer to stick with textbooks and peer-reviewed journal articles. How can we ensure that our teaching materials are both up to date, as well as trustworthy? And how can materials be (re)used across disciplines?

 References
 
 1. The educational model - Education - Utrecht University. n.d. https://www.uu.nl/en/education/educational-vision/the-educational-model (8 Apr. 2026, date last accessed).
 2. COSiE: Community for Open Science in Education. Open Science Community Utrecht n.d. https://openscience-utrecht.com/cosie/ (8 Apr. 2026, date last accessed).
 3. Mosteiro P, Oberman HI. Markup Languages and Reproducible Programming in Statistics. 26 Feb. 2026. https://mlarpis.github.io/markup/ (8 Apr. 2026, date last accessed).
 4. FORRT - Framework for Open and Reproducible Research Training. FORRT - Framework for Open and Reproducible Research Training. n.d. https://forrt.org/ (8 Apr. 2026, date last accessed).
 5. Community TTW. The Turing Way: A Handbook for Reproducible, Ethical and Collaborative Research. Zenodo, 14 Apr. 2025. https://doi.org/10.5281/zenodo.15213042.
 6. The Carpentries. The Carpentires. n.d. https://carpentries.org/ (8 Apr. 2026, date last accessed).
