---
title: "From methods research to methods guidance: an evolving collaborative research program"
---
**Speaker:** Malena Chiaborelli, University Hospital Basel

**Co-authors:** Julian Hirt (University of Bern), Matthias Briel (University Hospital Basel), Stefan Schandelmaier (University Hospital Basel)

### Abstract {.unlisted .unnumbered}

Methods guidance (MG) translates methods research into actionable advice for researchers. However, how to move from methods research to user-friendly and effective MG in a systematic and transparent way remains unclear. We address this problem through an evolving collaborative research program.

We established an initial database of MG ([www.lights.science](https://www.lights.science)). The database currently contains over 2000 MG articles that would otherwise be difficult to find and study. Meta-research on the database showed that only a fraction of MG articles reported details about the authors' expertise or the development process, rarely referring to methodological evidence.

In response, we established a systematic research program to explore strategies for developing MG and making MG more evidence-based and user-friendly: the STrategies for developing REseArch Methods guidance (STREAM) project includes literature reviews, interviews with MG users, an interdisciplinary panel, and user-testing of the new strategies.

While working on STREAM, we developed a living typology of methodological research. It provides definitions and a terminology for various methodological study types ([methods-research.org](https://methods-research.org)). Currently, we plan to develop guidance for performing, reporting, and appraising the different types of methodological studies.

At the symposium, we will provide an overview of the evolving research program, presenting results from our research on MG, user-interviews, the typology, and possible strategies for developing future MG (including artificial intelligence).
