---
title: "Crowdsourcing methodological comparisons: A many-analysts simulation study to identify conditions under which results in convenience samples generalize to target populations"
---
**Speaker:** Mona Niethammer, Ludwig Maximilian University of Munich

**Co-authors:** Carolin Strobl (University of Zurich), Anne-Laure Boulesteix (Ludwig Maximilian University of Munich; Munich Center of Machine Learning), Eiko I. Fried (Leiden University), Tim P. Morris (Novartis Pharmaceuticals UK Ltd), Christina Sauer (Ludwig Maximilian University of Munich), Edouard F. Bonneville (Ludwig Maximilian University of Munich; Munich Center of Machine Learning), Balazs Aczel (ELTE Eötvös Lorénd University), Suzanne Hoogeveen (Utrecht University), Alexandra Sarafoglou (University of Amsterdam), Sabine Hoffmann (Ludwig Maximilian University of Munich)

### Abstract {.unlisted .unnumbered}

Research on the replicability crisis in empirical psychology has shown that researcher degrees of freedom (RDF) are a large-scale problem. Many-analysts studies, in which independent research teams analyze the same data to address the same questions, have been used to reveal how analytical choices shape substantive conclusions, including, but not limited to, documenting the impact of RDF and exploring ways to mitigate them.

In this paper, we argue that similar problems exist in the methodological literature. Specifically, we show that RDF arising in methodological studies can substantially affect conclusions about method performance. Using a many-analysts simulation study, we demonstrate how different analysts, faced with the same underlying research question, may arrive at varying results depending on these decisions. Our case study focuses on the extent to which results obtained in convenience samples generalize to target populations.

We quantify between-analysts variability in methodological conclusions and show how many-analysts approaches can help identify and reduce overoptimistic and non-replicable claims in method evaluations. We conclude with practical recommendations for designing and organizing many-analysts simulation studies as a feasible tool to improve the robustness and replicability of methodological research.
