---
title: "The Do's and Don'ts of Benchmarking in Systems Biology"
---

**Speaker:** [Pablo Meyer Rojas](https://research.ibm.com/people/pablo-meyer-rojas), IBM

### Abstract {.unlisted .unnumbered}

Advances in experimental methods have generated increasingly larger and complex
biological datasets that are used to train A.I. models. These should ideally
predict reliably functional states of biological systems, including those
causing disease, that have not been directly observed or measured. A natural
question is how accurate these A.I. predictions are. This is not only a question
about scientific rigour as if clinical prediction models are inaccurate,
patients may be harmed. In drug development, bad predictions can cost hundreds
of millions of dollars. For any given task, hundreds of alternative A.I. methods
can now be rapidly developed, and we believe that a systematic assessment or
"benchmarking" is urgently needed. In order to mitigate the "self-assessment
trap", i.e unconscious bias towards favoring our own method, it is necessary to
decouple the method development from its assessment, akin to the evaluation of
drug's efficacy in a double-blind clinical trial. In this regard, we are
building on the success of DREAM (Dialogue for Reverse Engineering Assessments
and Methods) challenges performing "crowdsourced competitive challenges", where
tasks are posed in the public domain, and anyone is allowed to submit an answer
and will describe the lessons learned from more than 80 public challenge
competitions organized over the past 15 years. I will also describe how this has
led to create the BEACON (Benchmarking, Evaluation & Assessment Consortium) to
bring other competition-based approaches such as CASP, OpenADMET, CACHE and Sage
Bionetworks together.
