project:
  type: website
            
website:
    title: "MSMR 2027"
    page-navigation: true
    back-to-top-navigation: true
    page-footer:        
        left: |
          Made with [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) 
        
       
        right: |
           Licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) \
           \ Source code on [![](https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png){fig-alt="GitHub" width=30px}](https://github.com/lmu-ibe-bmm/msmr)
           
           
    #favicon: 'assets/Logo_CRS_col.svg'
    
    #site-url: https://crsuzh.pages.uzh.ch/msmr
    repo-url: https://github.com/lmu-ibe-bmm/msmr
    
    navbar:
        collapse-below: lg
        background: light
        
        right:                  
        #  - text: "Call for Contributions"
        #    href: ./call/index.qmd
        # - text: "Program"
        #    href: ./program/index.qmd
        #  - text: "Travel and Venue"
        #    href: ./travel/index.qmd
          - text: "Code of Conduct"
            href: ./code-of-conduct/index.qmd
          # - text: "Scientific Committee"
          #   href: ./committee/index.qmd
          - text: "Contact"
            href: ./contact/index.qmd

format:
    html:         
        grid:
          sidebar-width: 350px
        theme:
          light: [flatly, assets/custom-theme.scss]
          dark: [darkly, assets/custom-theme.scss]
        css: assets/custom-theme.scss
        toc: true
        toc-depth: 4
        toc-expand: 4
