---
title: "Poster Session"
subtitle: "31 August 2026: 16:10 – 17:30"
---

- Agata Bochynska, Mary Beth Neff: [Are pilot studies underreported? Preliminary findings from a meta-scientific assessment in psychology](posters/a-bochynska.html)
- Albie Duffy: [Mapping Psychology Preregistrations: A Subdiscipline Landscape of OSF Registrations, 2012-2025](posters/a-duffy.html)
- Alexandra Bannach-Brown: [Expanding the GALENOS Approach to Triangulating Evidence (GATE): A Framework for Integrating Evidence for Decision-Making in Psychiatry](posters/a-bannach-brown.html)
- Aljoscha Rimpler: [The Joint Effects of Measurement Error and Model Misspecification on Statistical Interactions](posters/a-rimpler.html)
- Alyssa Columbus: [How Much Evidence Is Enough? A Framework for Managing Data Reuse and Analytical Uncertainty in Repeated Data Analysis](posters/a-columbus.html)
- Barış Karahan: [Fishing for Significance: Hypothesis Testing Involving Multiple Testing with Bayesian and Frequentist Tools](posters/b-karahan.html)
- Bence Palfi: [PreCheck: An AI-Assisted Tool and Evaluation Framework for Preregistration Quality](posters/b-palfi.html)
- Dominik Dianovics: [Agent-based Models for Multi-analyst Studies](posters/d-dianovics.html)
- Gustavo Andres Marquez Flores: [Types of Statistical Arguments in Empirical Research in Psychology](posters/g-marquez-flores.html)
- Hanne Oberman: [Toward a standardized evaluation of imputation methodology](posters/h-oberman.html)
- Jack Fitzgerald: [Non-Robustness in Log-Like Specifications](posters/j-fitzgerald.html)
- Yury Shevchenko: [Open Lab Online: A Reproducible Platform for Cross-Disciplinary Methods Research](posters/y-shevchenko.html)
