# Code of Conduct {.unnumbered .unlisted}

We are dedicated to providing a supportive, collegial, and harassment-free conference experience for everyone, regardless of: gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age, or religion, intellectual position, approaches to data analysis, software preferences, coding style, scientific perspective, etc.

The Code of Conduct applies to this event, including but not limited to the talks, poster sessions, and social activities. We do not tolerate harassment, intimidation, or bullying of conference participants. Sexual language and imagery are not appropriate in presentations, communications, in online venues, including chats.

Conference participants violating these rules may be sanctioned or expelled from the conference at the discretion of the conference organizers.

### Examples of unacceptable harassment, intimidation, and bullying behavior {.unnumbered .unlisted}

Harassment includes, but is not limited to: Making comments in chats, to an audience or personally, that belittle or demean another person; harassing photography or recording;  sustained disruption of talks or other events; unwelcome sexual attention; advocating for, or encouraging, any of the above behavior.

Intimidation and bullying include, but are not limited to: aggressive or browbeating behavior directed at someone during a public presentation; mocking or insulting another person’s intellect, work, perspective, or question/comment; making reference to someone’s gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age, religion, or other personal attributes in the context of a scientific discussion; deliberately making someone feel unwelcome.

### Enforcement {.unnumbered .unlisted}

Participants asked to stop any harassing behavior are expected to comply immediately. If a participant engages in harassing behavior, event organizers retain the right to take any actions to keep the event a welcoming environment for all participants. This includes warning the offender or expulsion from the conference.

We expect participants to follow these rules at all event venues and event-related online activities.

### Reporting {.unnumbered .unlisted}

If someone makes you or anyone else feel unsafe or unwelcome, please report it as soon as possible to members of the local organizing committee (Anne-Laure Boulesteix, Moritz Herrmann, Marieke Stolte, Edouard Bonneville). Harassment and other code of conduct violations reduce the value of our event for everyone. We want you to be happy at our event. People like you make our event a better place.

When taking a personal report, our staff will ensure you are safe and cannot be overheard. They may involve other event staff to ensure your report is managed properly. Once safe, we’ll ask you to tell us about what happened. This can be upsetting, but we’ll handle it as respectfully as possible, and you can bring someone to support you. You won’t be asked to confront anyone, and we won’t tell anyone who you are.

Our team will be happy to help you contact hotel/venue security, local law enforcement, local support services, provide escorts, or otherwise assist you to feel safe for the duration of the event. We value your attendance.


### Source 

This code of conduct was adapted from the [Bioconductor project](https://www.bioconductor.org/about/code-of-conduct/){target="_blank"} and the [Modern Benchmarking conference](https://sites.google.com/view/ascona2025/coc?authuser=0){target="_blank"}.
