# Travel and Venue

### Conference location

[University of Zurich Main Building](https://www.plaene.uzh.ch/KOL), Room KOL-G-217, Rämistrasse 71, 8006 Zürich, Switzerland

### Getting to Zurich

Zurich can be reached by [train](https://www.sbb.ch/en/home.html) or by [airplane](http://www.zurich-airport.com/).

### Getting to the conference location

<!-- Map with workshop location and social event locations -->

The conference location can be reached from Zurich Main Station (Hauptbahnhof) via a 15 minute walk or within 10 minutes by tram lines 6 or 10. You can also take the Polybahn, a funicular railway, from Central (5 minute walk from the Main Station) to Polyterrasse ETH (5 minute walk to the conference location).

A network plan for the tram, bus and S-Bahn lines can be found [here](https://www.zvv.ch/zvv/de/home.html).

Tickets for all means of public transport within the city (including some boats and mountain railways) are available from the vending machines at each stop or the ticket counters located, e.g., at the train stations and the airport. 

### Food during the conference

Coffee, tea and snacks are provided at the conference venue during the morning
and afternoon breaks.

Lunch is not provided, but the university cafeteria ("Untere Mensa" in the
basement) is open from 11:00 to 14:30 and serves several hot dishes as well as a
salad buffet. There are also numerous cafes, bakeries, and take-away places
within a few minutes' walk of the venue.

### Conference dinner

The conference dinner takes place on Monday, 31 August 2026, starting at 18:30 at
the [ETH Dozentenfoyer](https://maps.app.goo.gl/E7FA8Hto3wHktKEa6), ETH-Zentrum,
Rämistrasse 101, 8092 Zürich, about a 5 minute walk up Rämistrasse from the
conference venue. It is a standing dinner ("Apéro riche") and is free of charge
for all registered participants, but registration for the dinner is required.

### Accommodation

There is no special conference rate but here are some examples for places to stay. The information below each link indicates walking time to the conference site (Rämistrasse 71), walking time to public transport stop serving tram lines 6, 9, 10 (which go directly to the conference site), and price category from $ to $$$.

- [Hotel Marta](https://en.hotelmarta.ch/): 11 min walk, 2 min tram 6/10 ($)
- [Hotel Bristol](https://www.hotelbristol.ch): 15 min walk, 4 min from tram 6/10 ($$)
- [Oldtown Hostel Otter](https://oldtownzurich.com/): 16 min walk, 3 min tram 8/9 ($)
- [Hotel Hottingen](https://www.hotelhottingen.ch/hotel-en/): 14 min walk, 4 min tram 8/9 ($$)
- [Sorell Hotel Rütli](https://www.sorellhotels.com/en/ruetli): 12 min walk, 2 min tram 6/10 ($$)
- [Swiss Chocolate Hotel](https://www.swisschocolatehotel.com): 12 min walk, 2 min tram 6/10 ($$)
- [Hotel Limmathof](https://www.limmathof.com): 12 min walk, 1 min tram 6/10 ($$)
- [Hotel Josef](https://hoteljosef.ch/en/): 25 min walk, 10 min tram 6/10 ($$$)
- [Sorell Hotel Rex](https://sorellhotels.com/de/rex/zuerich): 17 min walk, 7 min tram 6/10 ($$)
- [Guesthouse Zollhaus](https://www.guesthouse-zollhaus.ch/en): 30 min walk, 14 min tram 6/10 ($)
- [Kafi Schnaps Pension Hotel](https://www.kafischnaps.ch/en/hotel/hotel): 31 min walk, 1 min to bus 33 with transfer to tram 6/10 ($)
- [Zurich Youth Hostel](https://www.youthhostel.ch/de/hostels/zuerich/): 58 min walk, 7 min tram 7 or 2 min bus 72 with transfer to tram lines ($)

### Certificate of attendance

If you attended the conference in-person and require a certificate of
attendance, please contact us at
[msmr@psychologie.uzh.ch](mailto:msmr@psychologie.uzh.ch).

### Helpful information

#### Currency

In Switzerland, you pay with the Swiss Franc (CHF). Some shops and restaurants
in Zurich accept the Euro, but exchange rates are usually very bad. It is
therefore worthwhile to get CHF. The easiest way to do this is at ATMs. Most
shops and restaurants accept credit card and debit card payments.

#### Electricity

In Switzerland, the socket types C and J with 230 volts and 50 hertz frequency are used. Please check out in advance if you need an adaptor to be able to connect your laptop or other electronic devices to the Swiss socket types. Further Information: <https://www.power-plugs-sockets.com/switzerland/>

#### Internet

At UZH, you can use the internet via the wireless networks "eduroam" if supported by your institution (check login and password at your home institution) or "uzh-guest". More information is available on the [UZH central IT website](https://www.zi.uzh.ch/en/getting-started/guest.html).

#### Swimming

Zurich is known for its many possibilities for swimming and bathing. Many of them are free of charge. Starting in the north, the Werdinsel, a small island in the Limmat, is a popular place for nature lovers. More urban places are Oberer und Unterer Letten, or numerous places around the Lake of Zurich. More information is available on [Zurich Tourist Information website](https://www.zuerich.com/en/inform-plan/seasons-and-climate/zurich-in-summer/outdoor-pools-in-zurich).

#### Drinking Water

You can refill your drinking bottle from any tab and from the public fountains everywhere in the city. The water from the tap or any of the many fountains across the city has excellent drinking water quality.

#### Some nice places to eat or drink in Zurich

- [Hiltl Dachterasse](https://hiltl.ch/): Specialized in vegetarian food; also in other locations in Zurich ($$)
- [tibits Seefeld](https://www.tibits.ch/en/home): Specialized in vegetarian food; also in other locations in Zurich ($$)
- [Restaurant Alpenrose](http://www.restaurantalpenrose.ch/): Excellent, home-style cuisine with many Zurich and Swiss specialities ($$$)
- [Afghan Anar](https://www.afghananar.ch/): Delicious Afghan dishes ($$)
- [Confiserie Sprüngli](https://www.spruengli.ch/de/): Traditional cafe with French pastry ($$)
- [BQM](http://www.bqm-bar.ch/): Student cafe/bar near the main university building, mainly drinks ($)
- [Frau Gerolds Garten](https://www.fraugerold.ch/): Urban garden with drinks, food and views on the trains ($$)
- [Odeon](https://odeon.ch/en/): Old and famous bar in the city center ($$)
- [Franzos](https://franzos.ch/franzos/): French creperie and bistro at the river (\$-\$\$)
- [da PONE](https://www.dapone.ch/): "Top Pizzeria in Switzerland 2025" and "100 Top Pizza World 2025"; at the river ($$)
- [Mori Ramen](https://mori.ch/): Japanese ramen; close to university main building and art museum ($$)
- [Punto italiano](https://www.hellozurich.ch/de/spot/punto-italiano.html): Paninotecca and Focacceria; near university main building ($)
- [Kitchen Republik](https://www.kitchen-republic.ch/de/zuerich-west): Fusion kitchen ($$)
- [Die Waid](https://diewaid.ch/): Fine, home-style cuisine; one of the best views in Zurich ($$$)
- [Sternen Grill](https://www.sternengrill.ch/): Focus on sausages, hamburgers, etc. ($)
- [Zeughauskeller](https://www.zeughauskeller.ch/home): Traditional Swiss restaurant ($$)
- [Zum chalte Brunne](https://www.zumchaltebrunne.ch/): Ethical butcher with restaurant and lunch menu ($$)
- [Pizza Nation](https://pizzanation.ch/): Take-away Pizza ($)
- [Al Paso](https://alpaso.ch/): Sandwiches and salads; lunch only with limited seating options ($)
