---
title: "Learning Research System for Swiss Clinical Trials"
---

**Speaker:** [Matthias Briel](https://clinepi.dkf.unibas.ch/en/briel/), University of Basel

### Abstract

Randomized clinical trials (RCTs) are critical for evaluating clinical interventions. However, one out of four RCTs is prematurely discontinued in Switzerland, mostly due to poor recruitment of participants and particularly affecting investigator-initiated RCTs.(1-3) Results of one third of started investigator-initiated Swiss RCTs are not published in peer-reviewed publications or trial registries.(3) Systematic reviews of existing trials before starting a new RCT to show the knowledge gap and to inform the design of the new trial are typically lacking. Reasons include Swiss researchers’ perceptions that they are experts in the field who know all relevant research, the fact that systematic reviews are typically time-consuming, a lack of specific funds or personnel with suitable expertise, and no enforcement by funders and ethics committees.(4) Failure to address recruitment problems, non-publication of results, and non-consideration of existing evidence in RCTs wastes valuable resources, leaves important research questions unanswered, and diminishes the public’s trust in science. 
In my presentation at the conference, I will give examples of empirically conducted research on RCTs in Switzerland addressing the above-mentioned issues using quantitative, qualitative, interventional, or implementation science methods. I will show how meta-research can identify and monitor problems in the planning and conduct of RCTs that can then be addressed through produced outputs (e.g. tools, guidelines) by actors and stakeholders in the clinical research arena. I will outline a learning research system for the continuous improvement of Swiss RCTs where the output from meta-research is directly integrated in under- and postgraduate teaching and training courses of Swiss Clinical Trial Units and in their support services for clinical researchers. At the same time can teaching and consultation sessions with researchers reveal further unresolved issues in RCTs, that can trigger new meta-research. 


(1)	Kasenda B, von Elm E, You J, Blümle A, Tomonaga Y, Saccilotto R, Amstutz A, Bengough T, Meerpohl J, Stegert M, Tikkinen KAO, Neumann I, Carrasco-Labra A, Faulhaber M, Mulla S, Mertz D, Akl EA, Bassler D, Busse J, Ferreira-González I, Lamontagne F, Nordmann AJ, Gloy V, Raatz H, Moja L, Rosenthal R, Ebrahim S, Schandelmaier S, Sun X, Vandvik PO,  Johnston BC, Walter MA, Burnand B, Schwenkglenks M, Hemkens L, Bucher HC, Guyatt GH, Briel M. Prevalence, characteristics, and publication of discontinued randomized trials. JAMA 2014;311(10):1045-1051
(2)	Speich B, Gryaznov D, Gloy VL, Lohner S, Klatte K, Taji Heravi A, Ghosh N, Lee H, Mansouri A, Marian IR, Saccilotto R, Nury E, Griessbach AN, Schönenberger C, Mertz D, Busse JW, Blümle A, von Niederhäusern B, Hopewell S, Odutayo A, Briel M, and the ASPIRE study group. Non-registration, discontinuation, and non-publication of randomized trials: a repeated meta-research analysis. PloS Med 2022;19(4):e1003980
(3)	Speich B, Taji Heravi A, Schönenberger CM, Hausheer L, Gryaznov D, Busse JW, Covino M, Lohner S, Chiaborelli M, Schwenke J, Saccilotto R, von Elm E, Agarwal A, Hirt J, Mall D, Amstutz A, Epp S, Mertz D, Blümle A, von Niederhäusern B, Odutayo A, Griessbach AN,  Hopewell S, Briel M, and the ASPIRE study group. Non-registration, discontinuation, and non-publication of randomized trials: A systematic review. JAMA Network Open 2025;8(9):e2524440 
(4)	McLennan S, Nußbaumer-Streit B, Hemkens LG, Briel M. Barriers and facilitators for conducting systematic evidence assessments in academic clinical trials. JAMA Network Open 2021;4(11):e2136577

