---
title: "Designing Better Research Systems: How Research on Research informs science policy and assessment reforms"
---

**Speaker:** [Rachel Heyard](https://www.crs.uzh.ch/en/about-us/People/team/Rachel-Heyard.html), University of Zurich

### Abstract

Research assessment shapes not only careers and funding decisions but also the culture of research itself. However, many current assessment systems, based on publication metrics or the expectations of linear career trajectories, were never intentionally designed, and therefore often fail to value what truly contributes to rigorous, innovative, and socially valuable research. 

Research on Research (RoR) examines unintended consequences of these systems: risk-averse and biased funding patterns, peer-review inefficiencies, barriers for early career researchers, and the systematic undervaluation of invisible yet essential work, i.e., data stewardship, team science, and reproducibility efforts. But RoR can do more than identify shortcomings. It can, for example, highlight gaps, opportunities and pathways for reform. When given the means, RoR can serve as a missing link between science policymakers and researchers by providing evidence that captures real needs, pressures and perspectives across roles and career stages. Well designed RoR experiments, developed in collaboration with funders, journals and research institutions, can test new approaches and provide novel evidence to support more equitable and sustainable solutions. 

Drawing on my experience from working at the Swiss National Science Foundation, my research in meta-science, and my contribution to various research assessment working groups, I show how evidence generated through RoR can be translated into policy that supports culture change.

